### ISSUE TITLE
Configurar impressão das vias

### ISSUE THREAD

**Issue by ThalisonSantos** [SistemaFusion/Tef#6]
desculpe o meu desconhecimento, mas como faço para configurar as vias que serão impressão na transação?

**Comment by robertorp** [comment]
```
private void ImprimirViaAction(object sender, IImprimeViaEventArgs e)
        {
            if (e.IsTemViaUnica)
            {
                Console.Out.WriteLine(string.Empty);
                Console.Out.WriteLine(string.Empty);
                Console.Out.WriteLine("Via Única");
                foreach (var imagemComprovante in e.ViaUnica)
                {
                    Console.Out.WriteLine(imagemComprovante);
                }


                new ImprimirViaTef(e.ViaUnica, NomeImpressora.Text).Imprimir();
            }

            if (e.IsTemViaCliente)
            {
                Console.Out.WriteLine(string.Empty);
                Console.Out.WriteLine(string.Empty);
                Console.Out.WriteLine("Via Cliente");
                foreach (var imagemComprovante in e.ViaCliente)
                {
                    Console.Out.WriteLine(imagemComprovante);
                }

                new ImprimirViaTef(e.ViaCliente, NomeImpressora.Text).Imprimir();
            }

            if (e.IsTemViaEstabelecimento)
            {
                Console.Out.WriteLine(string.Empty);
                Console.Out.WriteLine(string.Empty);
                Console.Out.WriteLine("Via Estabelecimento");
                foreach (var imagemComprovante in e.ViaEstabelecimento)
                {
                    Console.Out.WriteLine(imagemComprovante);
                }

                new ImprimirViaTef(e.ViaEstabelecimento, NomeImpressora.Text).Imprimir();
            }


            if (e.IsTemViaReduzida)
            {
                Console.Out.WriteLine(string.Empty);
                Console.Out.WriteLine(string.Empty);
                Console.Out.WriteLine("Via Reduzida");
                foreach (var imagemComprovante in e.ViaReduzida)
                {
                    Console.Out.WriteLine(imagemComprovante);
                }

                new ImprimirViaTef(e.ViaReduzida, NomeImpressora.Text).Imprimir();
            }


            if (e.IsTemVia1)
            {
                Console.Out.WriteLine(string.Empty);
                Console.Out.WriteLine(string.Empty);
                Console.Out.WriteLine(string.Empty);
                Console.Out.WriteLine(string.Empty);
                Console.Out.WriteLine("Via Via1");
                foreach (var imagemComprovante in e.Via1)
                {
                    Console.Out.WriteLine(imagemComprovante);
                }

                new ImprimirViaTef(e.Via1, NomeImpressora.Text).Imprimir();
            }

            if (e.IsTemVia2)
            {
                Console.Out.WriteLine(string.Empty);
                Console.Out.WriteLine(string.Empty);
                Console.Out.WriteLine("Via Via2");
                foreach (var imagemComprovante in e.Via2)
                {
                    Console.Out.WriteLine(imagemComprovante);
                }

                new ImprimirViaTef(e.Via2, NomeImpressora.Text).Imprimir();
            }
        }
```

dentro do aplicativo de teste tem isso maninho

**Comment by ThalisonSantos** [comment]
@robertorp valeu!! só mais questão sabe dizer se funciona com Acqio TEF?

**Comment by robertorp** [comment]
Tem que testar, basta utilizar o tefdialhomologação , o framework hoje so atende com TEF Dial

**Comment by ThalisonSantos** [comment]
blz vou testar

**Comment by ThalisonSantos** [comment]
@robertorp fiz o teste com o Acqio TEF e funcionou a única observação foi o comprovante vou anexar um exemplo de como saiu.
[cup.pdf](https://github.com/SistemaFusion/Tef/files/5300231/cup.pdf)

**Comment by robertorp** [comment]
é assim mesmo, vc pode tirar as aspas duplas com um replace, ai basta você jogar onde quiser.. ele retorna um List de strings 
ai basta vc manipular onde melhor entender, lembrando que as letras etc.. etc.. tudo é gerado pelo TEF , não é o framework de gera, no caso as letras estranhas aí , deve ser alguma configuração do tef

**Comment by ThalisonSantos** [comment]
@robertorp você saberia como identificar esse caractere que vem no lugar do Ç ai em simulação? tentei removeAcentos mas não funcionou

**Comment by robertorp** [comment]
acho que isso é alguma configuração do monitor do tef aí .. alguma config , o ideal é ligar para eles antes de tudo, mas eu ligaria no suporte do tef para ver se existe alguma configuração do monitor aí sim pensariamos em mexer no framework se for algo relacionado a ele. Mas tudo o que o framework faz é ler o arquivo que eles retornam , se for algo relacionado a isso criamos alguma configuração para estar passando na leitura UTF8 , ASCII etc.. 

Existe a classe ImprimirViaTef onde vc passa a imagem em string[] array como mencionei , nomeImpressora , fonte se quiser . 

confira no debug se está tudo ok as letras, se retornam tudo ok as letras no debug 

código que faz o load do arquivo tef 
![image](https://user-images.githubusercontent.com/10251705/94595794-a5b33300-0261-11eb-82b1-297602553d4e.png)

**Comment by ThalisonSantos** [comment]
@robertorp estou com o suporte deles eles perguntaram se usavamos UTF8, imprimindo direto pelo tef sai normal

**Comment by robertorp** [comment]
Me passa o contato do pessoal do TEF? site.. é me diz como é o processo de homologação deles, para eu estar verificando aqui 
me chama no skype robertoalves18@hotmail.com
