### ISSUE TITLE
Erro na impressão

### ISSUE THREAD

**Issue by ThalisonSantos** [SistemaFusion/Tef#8]
estou recebendo alguns erros de impressão em clientes diferentes, alguém já passou por isso?

System.ArgumentException: A fonte 'Open Sans Condensed' não dá suporte ao estilo 'Regular'.
   em System.Drawing.Font.CreateNativeFont()
   em System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   em System.Drawing.Font..ctor(FontFamily family, Single emSize)
   em Tef.Infra.AdicionarTexto..ctor(Graphics graphics, String texto, Int32 tamanhoFonte, SolidBrush br, Font font)
   em Tef.Infra.ImprimirViaTef.<Imprimir>b__7_0(Object sender1, PrintPageEventArgs e1)
   em System.Drawing.Printing.PrintDocument.OnPrintPage(PrintPageEventArgs e)
   em System.Drawing.Printing.PrintDocument._OnPrintPage(PrintPageEventArgs e)
   em System.Drawing.Printing.PrintController.PrintLoop(PrintDocument document)
   em System.Drawing.Printing.PrintController.Print(PrintDocument document)
   em System.Drawing.Printing.PrintDocument.Print()
   em Tef.Infra.ImprimirViaTef.Imprimir()

System.ComponentModel.Win32Exception (0x80004005): Não foi emitida uma chamada a StartDocPrinter
   em System.Drawing.Printing.StandardPrintController.OnEndPrint(PrintDocument document, PrintEventArgs e)
   em System.Windows.Forms.PrintControllerWithStatusDialog.OnEndPrint(PrintDocument document, PrintEventArgs e)
   em System.Drawing.Printing.PrintController.Print(PrintDocument document)
   em System.Drawing.Printing.PrintDocument.Print()
   em Tef.Infra.ImprimirViaTef.Imprimir()

**Comment by robertorp** [comment]
Instale essa fonte https://github.com/SistemaFusion/Tef/tree/master/Fontes%20de%20texto%20para%20melhor%20legibilidade no sistema operacional do cliente e veja se resolve

**Comment by ThalisonSantos** [comment]
@robertorp eu já tinhas instalado essas fontes e mesmo assim o problema persistiu, consegui corrigir mudando a fonte para uma comum Tahoma
